import { describe, it, expect } from '@jest/globals';
import { part1, part2 } from './index';

const input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

describe('Day 7', () => {
    it('should solve example case for part 1', () => {
        expect(part1(input)).toBe(21);
    });

    it('should solve example case for part 2', () => {
        expect(part2(input)).toBe(0);
    });
});
